# Numerical settings shared by every solver backend
# The physical model is constructed seperately by the user and passed to the solver backend.

dtype: float64
device: cpu

# Real-space samples along lattice vectors a1 and a2
nx: 96
ny: 96

# Maximum harmonic indices along a1 and a2
m: 2
n: 2

# parallelogramic, circular
truncation: circular